version: '3'
services:
  # The Master node manages the UI and coordinates workers
  master:
    image: locustio/locust
    ports:
      - "8089:8089"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locust_py.py --master -H http://host.docker.internal:8080

  # The Worker node performs the actual load generation
  worker:
    image: locustio/locust
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locust_py.py --worker --master-host master